#Global Default values for the application
#Time is measured in SECONDS

cameraMoveDT: 10      # 20, Camera movement to viewpoint, ease in/out
fadeInDT: 3           # 5, Video opacity from 0 to 1
startDT: 1            # 1,Time delay between the end of the fading and the start of the video
playDT: 10            # 40, Video playback time
stopDT: 3             # 5, Time delay between end of video and start of the fade out
fadeOutDT: 2          # 5, Video from 1 to 0 opacity
waitUntilNextVideo: 0 # 0 Wait until the movement of the next video

resetViewTimeInMinutes: 6 # In the museum app, the App will restart to the 'Monument' viewpoint

# Eye-Dome-Lighting
radiousEDL: 1.0
strengthEDL: 0 # 0.1 ...


# Production settings are inside the .env file.
# They are needed at building time.

# Only for Development

stopSecuence: false # (true/false) stops the sequence to continue to the next video and helpt to reference the images
visiblePointCloud: true
showSubtitles: true
